// @sample @demo @reference — golden-records client generator (I-16A / DL-14).
//
// Derives the generated/shared client SOLELY from the canonical contract
// (`../golden-records.contract.ts`) via `initClient` + a validating `ApiFetcher`
// that re-parses the network-crossing response (DL-14 §5/§6). No hand-authored
// fetch DTOs. The canonical contract is the single source of truth; this file
// only projects it into a typed client and records provenance (canonical
// contract path + source SHA-256) so consumers can verify they import a
// contract-derived client and never a duplicated contract source.
//
// Mirrors packages/contracts/src/generation/generate-reference-flow-client.ts (I-11).

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
// src/generation/ -> contract at src/golden-records.contract.ts; generated at src/generated/
const contractPath = join(here, "..", "golden-records.contract.ts");
const generatedDir = join(here, "..", "generated");
const generatedPath = join(generatedDir, "golden-records-client.ts");

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function generatedClientSource(sourceSha256: string, canonicalContractPath: string, generatedClientPath: string): string {
  return `// AUTO-GENERATED by examples/starter-reference/generated-fixtures/golden-contracts/src/generation/generate-golden-records-client.ts. Do not hand edit.
// @sample @demo @reference — generated golden-records client (I-16A / DL-14).
//
// Derived ONLY from the canonical contract (../golden-records.contract.ts) via
// initClient + a validating ApiFetcher that re-parses the network-crossing
// response. No hand-authored fetch DTOs (DL-14 §5). The default in-process
// fetcher delegates to the real provider handler (golden-api fixture) so the
// contract→client→provider seam is exercised against the real ts-rest+zod
// runtime without a network — mirroring the proven I-11 reference-flow pattern.
import { initClient, validateResponse, type ApiFetcher } from "@ts-rest/core";
import { GoldenRecordsContract } from "../golden-records.contract.js";
import { handleGoldenRecordsApiRequest } from "../../../golden-api/src/provider/golden-records.provider.js";

export const GENERATED_CLIENT_PROVENANCE = {
  generator: "examples/starter-reference/generated-fixtures/golden-contracts/src/generation/generate-golden-records-client.ts",
  canonicalContractPath: ${JSON.stringify(canonicalContractPath)},
  sourceSha256: "${sourceSha256}",
  contractExport: "GoldenRecordsContract",
  generatedClientPath: ${JSON.stringify(generatedClientPath)}
} as const;

const goldenRecordsApiFetcher: ApiFetcher = async (args) => {
  const response = handleGoldenRecordsApiRequest({
    method: "POST",
    path: new URL(args.path).pathname,
    headers: args.headers,
    body: args.rawBody
  });
  return {
    status: response.status,
    body: response.body,
    headers: new Headers({ "content-type": "application/json" })
  };
};

function validatingApiFetcher(api: ApiFetcher): ApiFetcher {
  return async (args) => {
    const response = await api(args);
    if (args.validateResponse !== true) return response;
    const validated = validateResponse({ appRoute: args.route, response });
    return { status: validated.status, body: validated.body, headers: response.headers };
  };
}

export function createGoldenRecordsClient(api: ApiFetcher = goldenRecordsApiFetcher) {
  return initClient(GoldenRecordsContract, {
    baseUrl: "http://i16a.golden.local",
    validateResponse: true,
    throwOnUnknownStatus: true,
    api: validatingApiFetcher(api)
  });
}

export const goldenRecordsClient = createGoldenRecordsClient();
`;
}

export async function generateGoldenRecordsClient(): Promise<{ generatedClientPath: string; canonicalContractPath: string; sourceSha256: string }> {
  const contractSource = await readFile(contractPath, "utf8");
  const sourceSha256 = sha256(contractSource);
  await mkdir(generatedDir, { recursive: true });
  const canonicalContractPath = "examples/starter-reference/generated-fixtures/golden-contracts/src/golden-records.contract.ts";
  const generatedClientPath = "examples/starter-reference/generated-fixtures/golden-contracts/src/generated/golden-records-client.ts";
  await writeFile(generatedPath, generatedClientSource(sourceSha256, canonicalContractPath, generatedClientPath), "utf8");
  return { generatedClientPath, canonicalContractPath, sourceSha256 };
}

const invokedPath = process.argv[1] ?? "";
if (invokedPath.endsWith("generate-golden-records-client.ts") || invokedPath.endsWith("generate-golden-records-client.js") || invokedPath.endsWith("generate-golden-records-client.mjs")) {
  const result = await generateGoldenRecordsClient();
  console.log(JSON.stringify(result, null, 2));
}
