/* vibe-engineer-generated:start {"schematicId":"fixture.generic-structure","schematicVersion":"1.0.0","blockId":"code","inputFingerprint":"sha256:f43cd26f724356a82c055ad8af01674e0c24e51b4a41ae9dbfe85ffab23518c8","templateFingerprint":"sha256:46fb7314b245a442bb806e7c450b2a5b869d696066aaedd09079886c2536c56f"} */
Generated by fixture.generic-structure for Example Module.

export function createExampleModuleRecord(input) {
  return {
    kind: "example-module",
    title: "Example Module",
    value: input
  };
}
/* vibe-engineer-generated:end */
