export const ValidationErrorCode = Object.freeze({
  CARRIER_NOT_JSON: 'CARRIER_NOT_JSON',
  JSON_PARSE_ERROR: 'JSON_PARSE_ERROR',
  NOT_OBJECT: 'NOT_OBJECT',
  REQUIRED: 'REQUIRED',
  UNKNOWN_FIELD: 'UNKNOWN_FIELD',
  TYPE: 'TYPE',
  CONST: 'CONST',
  ENUM: 'ENUM',
  PATTERN: 'PATTERN',
  MIN_LENGTH: 'MIN_LENGTH',
  MIN_ITEMS: 'MIN_ITEMS',
  MIN_PROPERTIES: 'MIN_PROPERTIES',
  PROPERTY_NAME: 'PROPERTY_NAME',
  SCHEMA_VALIDATION: 'SCHEMA_VALIDATION',
  UNSUPPORTED_VERSION: 'UNSUPPORTED_VERSION',
  ARTIFACT_KIND_MISMATCH: 'ARTIFACT_KIND_MISMATCH',
  BAD_LINK: 'BAD_LINK',
  BAD_STATUS_HANDOFF: 'BAD_STATUS_HANDOFF',
  EVIDENCE_FOR_REQUIRED: 'EVIDENCE_FOR_REQUIRED',
  EVIDENCE_LINK_REQUIRED: 'EVIDENCE_LINK_REQUIRED',
  VERIFICATION_CATALOG_INCOMPLETE: 'VERIFICATION_CATALOG_INCOMPLETE',
  BLOCKED_ITEM_METADATA_REQUIRED: 'BLOCKED_ITEM_METADATA_REQUIRED',
  NOT_APPLICABLE_RATIONALE_REQUIRED: 'NOT_APPLICABLE_RATIONALE_REQUIRED',
  MALFORMED_EXTENSION: 'MALFORMED_EXTENSION',
  SCHEMA_INTERNAL_ERROR: 'SCHEMA_INTERNAL_ERROR'
});

export function makeValidationError({ artifactPath, artifactKind, schemaId, schemaVersion, pointer, code, message }) {
  return {
    artifactPath: artifactPath ?? null,
    artifactKind: artifactKind ?? null,
    schemaId: schemaId ?? null,
    schemaVersion: schemaVersion ?? null,
    pointer: pointer || '',
    code,
    message
  };
}
